spring:
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:juntas
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
